/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:ebabab96-8b5e-415d-8abe-a9a739c4f71e",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_ZjbPp7Y9s",
    "aws_user_pools_web_client_id": "6pj0e3a54scq7kuufcrc9mkq65",
    "oauth": {}
};


export default awsmobile;